// Auto-generated for Replit development environment.
// In production, this is generated by generate-config.js at Cloudflare Pages build time.
window.CP_CONFIG = {
  "BACKEND_URL": "",
  "GEOAPIFY_API_KEY": "",
  "LISTING_SITE_URL": "https://choice-properties-site.pages.dev"
};
