// ============================================================
  // Choice Properties — Application Form Config Generator
  // Runs at Cloudflare Pages build time to inject secrets into config.js
  // NEVER edit config.js directly — edit this file instead
  // config.js is gitignored; it is generated fresh on every deploy
  // ============================================================
  const fs = require('fs');

  const config = {
    // Google Apps Script backend URL — handles form submissions
    BACKEND_URL: (() => {
      if (!process.env.BACKEND_URL) {
        console.error('❌ BACKEND_URL environment variable is required but not set.');
        console.error('   Set it in Cloudflare Pages → Settings → Environment Variables.');
        process.exit(1);
      }
      return process.env.BACKEND_URL.replace(/\/$/, '');
    })(),
    // Geoapify key for address autocomplete — set in Cloudflare Pages env vars
    GEOAPIFY_API_KEY: process.env.GEOAPIFY_API_KEY || '',
    // Base URL of the listing platform — used for back-to-listing links
    LISTING_SITE_URL: (process.env.LISTING_SITE_URL || 'https://choice-properties-site.pages.dev').replace(/\/$/, ''),
    // Development-only utilities. Must remain false in public production builds.
    ENABLE_DEV_TOOLS: process.env.ENABLE_DEV_TOOLS === 'true',
  };

  const missing = [];
  if (!config.GEOAPIFY_API_KEY) missing.push('GEOAPIFY_API_KEY');

  if (missing.length) {
    console.warn('⚠  Missing optional env vars:', missing.join(', '));
    console.warn('   Address autocomplete will be disabled until GEOAPIFY_API_KEY is set.');
  }

  const configJs = `// Auto-generated by generate-config.js — do not edit directly.
  // This file is produced at Cloudflare Pages build time from environment variables.
  window.CP_CONFIG = ${JSON.stringify(config, null, 2)};
  `;

  fs.writeFileSync('config.js', configJs);
  console.log('✅ config.js written');
  